# Generated by Django 6.0.5 on 2026-06-28 10:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_recentlyplayed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="song",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
